### ISSUE TITLE
Could Not Parse DICOM

### ISSUE THREAD

**Issue by austinarose** [GoogleCloudPlatform/dicomweb-wsi-viewer#4]
I have good DICOM files that don't work in this utility. I'm getting an error when selecting a study that says: "localhost:8000 says - Could not parse DICOM fort study, possible reason: DICOM is not pathology or damaged image."

The same DICOM file works in demo.eunity.app

**Comment by pkling** [comment]
Thanks for reporting!

This viewer is primarily for pathology/whole slide images (WSI).

Could you confirm if the images you were trying to view were of that format?

**Comment by EduardoSantanaSeverino** [comment]
Dear @pkling , thanks for your response. 

Do you know about any other Viewer that works out of the box with Google Healthcare API? Something similar to this viewer. 

As this viewer is so simple. if you follow read me file, it works in seconds. 

But, If I have DICOM files in the Google Healthcare API this viewer is showing the same error described by @austinarose 

So any suggestion? or Comments?

Warm Regards, 
Eduardo

**Comment by pkling** [comment]
Hi Eduardo,

This viewer is primarily for pathology/whole slide images (WSI).

For other types of images (e.g., radiology), you can try OHIF or Weasis, both of which are open source viewers integrated with the Cloud Healthcare API.

https://github.com/OHIF/Viewers
https://github.com/nroduit/Weasis

For Weasis, you'll need to use the plugin here:

https://github.com/GoogleCloudPlatform/weasis-chcapi-extension

You can also try the commercial viewers IMS and eUnity:

https://cloudview.imstsvc.com
https://demo.eunity.app

I hope this helps.

Patrick
